---
galaxy_info:
  author: Chris White
  description: This role should includes anything that should be the same across each and every system.
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
