---
galaxy_info:
  author: Chris White
  description: Ansible role to install and setup my general apps
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system