---
galaxy_info:
  author: Chris White
  description: Install and configure third-party apps
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - geerlingguy.ansible-role-mas
