---

- hosts: localhost
  connection: local

  # Tasks
  tasks:

    - name: install personal homebrew cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - atom
        - coderunner

  # Roles (required)
  roles:

    - profile-all

  # Variables
  vars:

    # Computer
    # Name (used by superlumic-computername)
    - computername: cportable # (defaulted)

    # macOS Defaults (used by superlumic-osx-defaults)
    - osx_defaults: 
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: false

    # Git Settings (used by superlumic-homebrew)
    - git_user_name: Chris White                  # (defaulted)
    - git_user_email: chris@christopherdwhite.com # (defaulted)

  vars_files:
    - vars/macOS_defaults.yml