---

# Superlumic Playbook ==========================================================
#
# Superlumic configuration for setting up my production system quickly and making sure everything remains in compliance
#
# Note: I have tagged lines as (defaulted) below where the role has default settings that will be used if you do not set them.
#       Unless you want defaults make sure they are set.
#
- name: superlumic    # Playbook name
  hosts: localhost    # Run on localhost
  connection: local   # Run locally
  # gather_facts: false # Disable gather facts for faster execution if not needed
  # strategy: debug     # Enable debugger for failed tasks
  # remote_user: root   # User to run tasks as

  # Variables ==================================================================
  #
  # Set configuration variables passed to templates & included playbooks
  #
  vars:

    # Computer Name (used by superlumic-computername module)
    - computername: cportable # (defaulted)

  # Variable Files =============================================================
  #
  # Specifies a list of YAML files to load variables from.
  #
  # vars_files:

  # Tasks ======================================================================
  #
  # A list of tasks to perform in this playbook.
  #
  tasks:
    - user:
        name: cwhite

  # Roles ======================================================================
  #
  # The roles each of my Ansible managed clients may be setup for
  #
  roles:

    # ## Roles: Common ---------------------------------------------------------
    #
    # This role should includes anything that should be the same across each and every system.
    #
    - common

    # ## Roles: Workstation ----------------------------------------------------
    #
    # This is my primary working computer role with everything I want on my day-to-day
    # This role uses dependencies to organize and modularize into sub-roles by focus or actions
    #
    - workstation

    # ## Roles: Clients --------------------------------------------------------
    #
    # These are configuration roles that will setup things I need only for a specefic client
    # This role uses dependencies to organize and modularize into sub-roles by client
    #
    - clients

    # ## Contextual Profiles ---------------------------------------------------
    #
    # These are profiles that will change my workstation depending on what I'm working on.
    # For example, if I'm working on a PHP project I may want different dev packages in Atom or Sublime
    #
