---

- hosts: localhost
  connection: local

  # Tasks
  tasks:

    - name: install personal homebrew cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - atom
        - coderunner

  # Roles (required)
  roles:
    
    - profile-all

  # Variables
  vars:

    ## Computer
    - computername: cportable
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: false

    ## Git
    - git_user_name: Chris White
    - git_user_email: chris@christopherdwhite.com