---

# workstation-apps: tasks ======================================================
#
# Install and configure third-party apps
#

# Include Variable Files
- name: Include vars from casks.yml as {{ casks }}
  include_vars:
    file: "{{ item.file }}"
    name: "{{ item.name | default(omit) }}"
  with_items:
    - { file: 'casks.yml', name: 'casks' } # homebrew casks variable file
    - { file: 'homebrew.yml', name: 'homebrew' } # homebrew variable file
    - { file: 'sync.yml', name: 'sync' } # application sync variable file
    - { file: 'preferences.yml', name: 'preferences' } # application sync variable file

- name: Include base vars from variable files
  include_vars: 'app-store.yml'

- name: print local $path
  debug: msg="{{ mas_installed_apps }}"

# Homebrew Taps
- homebrew_tap:
    name: caskroom/versions

# Install formulas from Homebrew
- homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ homebrew.shell }}"
    - "{{ homebrew.bash }}"

# Install apps from Homebrew Cask
- name: Install Homebrew Cask Apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ casks.casks }}"

# Symlink application data to or from iCloud
- name: Symlink application data from iCloud
  file:
    src:   "{{ item.src | default(omit) }}"
    path:  "{{ item.path }}"
    force: "{{ item.force | default(true) }}"
    group: "{{ item.group | default(omit) }}"
    mode:  "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    state: "{{ item.state | default('link') }}"
  with_items:
    - "{{ sync.symlinks }}"
  become: true

# Set app preferences
- name: Write app defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type | default(omit) }}"
    array_add: "{{ item.array_add | default(false) }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items:
    - "{{ preferences.defaults }}"
  ignore_errors: true

# - name: Install Mac App Store Apps
#   mas_installed_apps: []
