---

# Include Variable Files
- name: Include vars from casks.yml as {{ casks }}
  include_vars:
    file: "{{ item.file }}"
    name: "{{ item.name }}"
  with_items:
    - { file: 'cask.yml', name: 'casks' } # homebrew casks variable file
    - { file: 'homebrew.yml', name: 'homebrew' } # homebrew variable file
    # - { file: 'app-store.yml', name: 'appstore' } 

# Tap Homebrew
- homebrew_tap:
    name: caskroom/versions

# Install apps from Homebrew Cask
- name: Install Homebrew Cask Apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - "{{ casks.cloud }}"
    # - "{{ casks.design }}"
    - "{{ casks.dev }}"
    - "{{ casks.productivity }}"
    - "{{ casks.social }}"
    - "{{ casks.utilities }}"
    - "{{ casks.web }}"
    - "{{ casks.write }}"
    # - "{{ casks.test }}"
