---

# Include Variable Files
- name: Include vars from casks.yml as {{ casks }}
  include_vars:
    file: cask.yml
    name: casks

# Tap Homebrew
- homebrew_tap:
    name: caskroom/versions

# Install apps from Homebrew Cask
- name: Install Homebrew Cask Apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - "{{ casks.cloud }}"
    # - "{{ casks.design }}"
    - "{{ casks.dev }}"
    - "{{ casks.productivity }}"
    - "{{ casks.social }}"
    - "{{ casks.utilities }}"
    - "{{ casks.web }}"
    - "{{ casks.write }}"
    # - "{{ casks.test }}"
