---

# Include Variable Files
- name: Include Vars from casks.yml as Casks
  include_vars:
    file: cask.yml
    name: casks

# Tap Homebrew
- homebrew_tap:
    name: caskroom/versions

# Install apps from Homebrew Cask
- name: Install Homebrew Cask Apps
  homebrew_cask: name={{item}} state=present
  with_items:
    - "{{ casks.dev }}"



- name: Test
  package:
    name: an-old-hope-syntax
    state: latest
    use: apm