---

# Include Variable Files
- name: Include vars from casks.yml as {{ casks }}
  include_vars:
    file: "{{ item.file }}"
    name: "{{ item.name }}"
  with_items:
    - { file: 'cask.yml', name: 'casks' } # homebrew casks variable file
    - { file: 'homebrew.yml', name: 'homebrew' } # homebrew variable file
    # - { file: 'app-store.yml', name: 'appstore' }
    - { file: 'sync.yml', name: 'sync' } # application sync variable file

# Homebrew Taps
- homebrew_tap:
    name: caskroom/versions

# Install formulas from Homebrew
- homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ homebrew.bash }}"

# Install apps from Homebrew Cask
- name: Install Homebrew Cask Apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ casks.cloud }}"
    # - "{{ casks.design }}"
    - "{{ casks.dev }}"
    - "{{ casks.productivity }}"
    - "{{ casks.social }}"
    - "{{ casks.utilities }}"
    - "{{ casks.web }}"
    - "{{ casks.write }}"
    # - "{{ casks.test }}"

# Symlink application data from iCloud
- name: Symlink application data from iCloud
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: "{{ item.force | default(true) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    state: link
  with_items:
    - "{{ sync.symlinks }}"
