---

- name: Include Vars from casks.yml as Casks
  include_vars:
    file: cask.yml
    name: casks

# Install apps from Homebrew Cask
- name: Install Homebrew Cask Apps
  homebrew_cask: name={{item}} state=present
  with_items:
    - "{{ casks.dev }}"