---
galaxy_info:
  author: Chris White
  description: Sets natural scrolling to off since nesting inverts it
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
