---

# dotfiles =====================================================================
#
# Dotfile Symlink Details
#
dotfiles:

  ## dotfiles: bash
  - { src: '/Users/cwhite/Source/csystems/dotfiles/.alias', dest: '~/.alias' }               # .alias        | Aliases
  - { src: '/Users/cwhite/Source/csystems/dotfiles/.bash_profile', dest: '~/.bash_profile' } # .bash_profile |
  - { src: '/Users/cwhite/Source/csystems/dotfiles/.env', dest: '~/.env' }                   # .env          | Environment Variables
  - { src: '/Users/cwhite/Source/csystems/dotfiles/.functions', dest: '~/.functions' }       # .functions    | Functions
  - { src: '/Users/cwhite/Source/csystems/dotfiles/.inputrc', dest: '~/.inputrc' }           # .inputrc      |
  - { src: '/Users/cwhite/Source/csystems/dotfiles/.prompt', dest: '~/.prompt' }             # .prompt       | Prompt Configuration
  - { src: '/Users/cwhite/Source/csystems/dotfiles/.bashrc', dest: '~/.bashrc' }             # .bashrc       | 

  ## dotfiles: git
  - { src: '/Users/cwhite/Source/csystems/dotfiles/git/.gitconfig', dest: '~/.gitconfig' }   # .gitconfig    | Prompt Configuration

  ## dotfiles: apps
  - { src: '~/Source/csystems/dotfiles/.hyper.js', dest: '~/.hyper.js' }                     # .hyper.js     | Hyper
