---
galaxy_info:
  author: Chris White
  description: Ansible role to install and configure your basic Sublime Text setup with preferences set, packages installed and kept up to date
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - roderik.superlumic-homebrew
  - roderik.superlumic-sublimetext
