---

# Install Atom from Homebrew Cask if necessary
- name: Install Atom from Homebrew Cask if necessary
  homebrew_cask: name="atom" state=present

# Make sure Atom and apm are installed, fail if not installed
- name: Ensure Atom and apm (Atom Package Manager) are installed
  command: which atom apm
  register: atom_status
  failed_when: atom_status.rc
  changed_when: false
  check_mode: no

- name: "apm clean : delete unused packages in node_modules"
  command: apm clean
  when: clean

- name: "apm config : configure items and preferences"
  command: "apm config {{ item.command }}"
  when: 
    - item.command | default(false)
    - item.command != "edit"
  with_items: "{{ config }}"

- name: "apm dedupe : deduplicate node_module packages"
  command: "apm dedupe {{ item }}"
  when: item
  with_items: "{{ dedupe }}"

# - name: "apm install package : install Atom packages"
#   command: "apm install {{ item }}"
#   ignore_errors: true
#   register: packages_status
#   with_items: "{{ packages }}"

# - name: "apm install package.txt : install Atom packages from file"
#   command: "apm install --package-file {{ role_path }}{{ item }}"
#   ignore_errors: true
#   register: package_files_status
#   with_items: "{{ package files }}"
