---

# Install Atom from Homebrew Cask if necessary
- name: Install Atom from Homebrew Cask if necessary
  homebrew_cask: name="atom" state=present

# Make sure Atom and apm are installed, fail if not installed
- name: Ensure Atom and apm (Atom Package Manager) are installed
  command: which atom apm
  register: atom_status
  failed_when: atom_status.rc
  changed_when: false
  check_mode: no

# apm clean: Delete packages in node_modules not in use
- name: apm clean
  command: apm clean
  when: apm_clean == true

# Run apm config
- name: Run apm config set loop
  command: "apm config {{ item.command }} {{ item.key | default(omit) }} {{ item.value | default(omit) }}"
  register: apm_config_output
  when: 
    - item.config
  with_items:
    - "{{ apm_config }}"

- debug: 
    msg: "'{{ item.stdout }}'"
  with_items:
    - "{{ apm_config_output.results }}"