---

# - name: Install Atom if necessary
#   command: which atom apm
#   register: return_value

  # check_mode: no
  # failed_when: return_value.rc
  # changed_when: False
  # environment:
  #   PATH: "{{ bin_dir }}:{{ ansible_env.PATH }}"

- shell: which atom apm
  register: return_value

# - shell: echo "Atom Installed-- {{ return_value.stdout }}"
#   when: return_value.stdout_lines

- debug: msg="{{ return_value.stdout_lines }}"

- debug: msg="Installed"
  when: return_value.stout != -1

- debug: msg="Not Installed"
  when: return_value.stout = -1

# # Ensure Atom is installed
# - name: Install Atom from Homebrew Cask if necessary
#   homebrew_cask: name=atom state=present"