---

# Check if Atom is installed
- name: Check if Atom and apm are installed
  command: which atom apm
  register: atom_status
  check_mode: no
  ignore_errors: yes

- debug: msg="{{ atom_status }}"

# - name: Install Atom if necessary
#   command: which atom apm
#   register: return_value

    # failed_when: return_value.rc
    # changed_when: False
    # environment:
    #   PATH: "{{ bin_dir }}:{{ ansible_env.PATH }}"

# - shell: echo "Atom Installed-- {{ return_value.stdout }}"
#   when: return_value.stdout_lines
# - debug: msg="{{ return_value_negative }}"

# - debug: msg="Installed"
#   when: return_value.stout != -1

# - debug: msg="Not Installed"
#   when: return_value.stout = -1

   # - name: check contents for emptiness
   #      debug: msg="Directory is empty"
   #      when: contents.stdout == ""

# # Ensure Atom is installed
# - name: Install Atom from Homebrew Cask if necessary
#   homebrew_cask: name=atom state=present"