---

# Install Atom from Homebrew Cask if necessary
- name: Install Atom from Homebrew Cask if necessary
  homebrew_cask: name="atom" state=present

# Make sure Atom and apm are installed installed, fail if not installed
- name: Ensure Atom and apm (Atom Package Manager) are installed
  command: which atom apm
  register: atom_status
  failed_when: atom_status.rc
  changed_when: false
  check_mode: no