---

# Check if Atom is installed
- name: Ensure Atom is installed
  command: which atom apm null
  register: atom_status
  failed_when: atom_status.rc
  changed_when: false
  check_mode: no

# Ensure Atom is installed
# - name: Install Atom from Homebrew Cask if necessary
#   homebrew_cask: name=atom state=present"