---
galaxy_info:
  author: Chris White
  description: Ansible role for my primary working computer with everything I want to set up for my day-to-day system. This role primarily just references other roles as dependencies for modularization.
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
  dependencies:
    - { role: '/usr/local/superlumic/config/roles/workstation_preferences' }