---

# workstation-dotfiles: tasks ==================================================
#
# Clone dotfiles repo and symlink them into place
#

# clone dotfiles repo
- git:
    repo: 'git@github.com:christopherdwhite/dotfiles.git'
    dest: '~/Source/csystems/dotfiles'
    clone: yes
    update: no

# Symlink dotfiles into position
- name: Symlink dotfiles into position
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: "{{ item.force | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    state: link
  with_items:
    - "{{ dotfiles }}"
