---

# Symlinks =====================================================================
#
# Application files and folders that need symlinked to or from iCloud Drive
#
symlinks:

## Symlinks: Productivity

### Symlinks: Productivity: 1Password
- path:  '/Users/cwhite/Library/Containers/net.shinyfrog.bear/Data/Library/Preferences/'
  state: 'directory'
- src:   '/Users/cwhite/Library/Mobile Documents/com~apple~CloudDocs/Application Sync/Bear/Containers/net.shinyfrog.bear/Data/Library/Preferences/net.shinyfrog.bear.plist'
  path:  '/Users/cwhite/Library/Containers/net.shinyfrog.bear/Data/Library/Preferences/net.shinyfrog.bear.plist'

### Symlinks: Productivity: Bear
- src:   '/Users/cwhite/Library/Mobile Documents/com~apple~CloudDocs/Application Sync/1Password/Preferences/com.agilebits.onepassword4.plist'
  path:  '/Users/cwhite/Library/Preferences/com.agilebits.onepassword4.plist'


## Symlinks: Utilities

### Symlinks: Utilities: Alfred
- path:  '/Users/cwhite/Library/Application Support/Alfred 3/Databases'
  state: 'directory'
- src:   '/Users/cwhite/Library/Mobile Documents/com~apple~CloudDocs/Application Sync/Alfred/Application Support/Databases/clipboard.alfdb'
  path:  '/Users/cwhite/Library/Application Support/Alfred 3/Databases/clipboard.alfdb'
- src:   '/Users/cwhite/Library/Mobile Documents/com~apple~CloudDocs/Application Sync/Alfred/Application Support/Databases/urlhistory.alfdb'
  path:  '/Users/cwhite/Library/Application Support/Alfred 3/Databases/urlhistory.alfdb'
- src:   '/Users/cwhite/Library/Mobile Documents/com~apple~CloudDocs/Application Sync/Alfred/Application Support/usage.data'
  path:  '/Users/cwhite/Library/Application Support/Alfred 3/usage.data'
- src:   '/Users/cwhite/Library/Mobile Documents/com~apple~CloudDocs/Application Sync/Alfred/Application Support/license.plist'
  path:  '/Users/cwhite/Library/Application Support/Alfred 3/license.plist'

### Symlinks: Utilities: Forklift
- src:   '/Users/cwhite/Library/Mobile Documents/com~apple~CloudDocs/Application Sync/Forklift/Preferences/com.binarynights.ForkLift-3.plist'
  path:  '/Users/cwhite/Library/Preferences/com.binarynights.ForkLift-3.plist'
- src:   '/Users/cwhite/Library/Mobile Documents/com~apple~CloudDocs/Application Sync/Forklift/Application Support/ForkLift'
  path:  '/Users/cwhite/Library/Application Support/ForkLift'
