---
galaxy_info:
  author: Chris White
  description: Sets up git and clones active projects
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
