---
galaxy_info:
  author: Chris White
  description: Configure git for system and clone long-term persistent repositories
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
