---

# - name: tap caskroom/versions
#   homebrew_tap: tap=caskroom/versions state=present

# - name: install developer brew applications
#   homebrew: name={{item}} state=latest
#   with_items:
#     - wget
#     - pwgen
#     - xmlstarlet
#     - htop
#     - watch
#     - rsync

- name: Setup default preferences
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "KeyRepeat"
    type: int
    value: 2
