---

- name: Write macOS defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    array_add: "{{ item.array_add | default(false) }}"
    value: "{{ item.value }}"
  with_items:
    - { domain: "NSGlobalDomain", key: "ApplePressAndHoldEnabled", type: "boolean", value: "true" } # Character accents popup on, key repeate off