---

# Setup default preferences in macOS
- name: Write macOS defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type) }}"
    array_add: "{{ item.array_add | default(false) }}"
    value: "{{ item.value | default(\"This shouldn't exist\") }}"
    state: "{{ item.state | default(\"present\") }}"
  with_items:
    - "{{ defaults }}"
  notify: "restart macos preferences"

# There are some settings, like those in /library/ that require escalated privileges
- name: Write macOS defaults with escalated privileges
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type | default(string) }}"
    array_add: "{{ item.array_add | default(false) }}"
    value: "{{ item.value | default(\"This shouldn't exist\") }}"
    state: "{{ item.state | default(\"present\") }}"
  with_items:
    - "{{ become_defaults }}"
  notify: "restart macos preferences"
  become: true