---

- name: Write macOS defaults
  osx_defaults:
    domain: "{{ item.0.domain }}"
    key: "{{ item.0.key }}"
    type: "{{ item.0.type }}"
    array_add: "{{ item.0.array_add | default(false) }}"
    value: "{{ item.0.value }}"
  with_items:
    - {{ defaults }}