---

# Set computer name
# - hostname:
#     name: "{{ name }}"

# Setup default preferences in macOS
- name: Write macOS defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type | default(omit) }}"
    array_add: "{{ item.array_add | default(false) }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items:
    - "{{ defaults }}"
  notify: "restart macos preferences"
  ignore_errors: true

# There are some settings, like those in /library/ that require escalated privileges
- name: Write macOS defaults with escalated privileges
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type | default(omit) }}"
    array_add: "{{ item.array_add | default(false) }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  with_items:
    - "{{ become_defaults }}"
  notify: "restart macos preferences"
  become: true
  ignore_errors: true

# Set two dimensional dict defaults through shell commands
- name: Set two dimensional dict defaults through defaults write
  command: defaults write '{{ item.domain }}' '{{ item.key }}' -{{ item.type }} {{ item.dict_string }}
  with_items:
    - "{{ dictionaries }}"

# Set Bing as Default Search Engine
- name: Execute a complex default variable
  command: "defaults write -g NSPreferredWebServices '{NSWebServicesProviderWebSearch = { NSDefaultDisplayName = Bing; NSProviderIdentifier = \"com.bing.www\"; }; }\\';"
  ignore_errors: true

# Enable Gatekeeper
- name: Enable Gatekeeper
  command: 'spctl --master-enable'
  become: true
