---

# - name: tap caskroom/versions
#   homebrew_tap: tap=caskroom/versions state=present

# Install apps from Homebrew Cask
- name: install personal homebrew cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - dash3

- name: Setup default preferences
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "AppleInterfaceStyle"
    type: string
    value: dark
