---

### apm_defaults
#
# Playbook attribute: apm_clean
# Default: false
# Required: no
# Description:
#   Runs `apm clean`
#   Command --help:
#     Deletes all packages in the node_modules folder that are not referenced as a dependency in the package.json file.
#
apm_clean: true