---

### apps-atom Variables
# 
# Overview: Configure the preferences and packages that Atom uses
#
# Description:
#   Define your preferences for Atom below, default variables have been set but are set to be as neutral and nondestructive as possible
# 
###

### clean
#
# Playbook attribute: clean
# Required: no
# Type: boolean
# Default: false
# Description:
#   Runs `apm clean`
#   Command --help:
#     Deletes all packages in the node_modules folder that are not referenced as a dependency in the package.json file. 
#       Note that this command is used for developing Atom packages and has been added for completeness, it's not something you normally use.
#
clean: false

### config
#
# Playbook attribute: config
# Required: no
# Type: array
# Default: false
# Description:
#   Runs `apm config {{ config.command }} {{ config.key }} {{ config.value }}`
#   Command --help:
#     Usage: apm config set <key> <value>
#            apm config get <key>
#            apm config delete <key>
#            apm config list
#            apm config edit
# Note:
#   While you can execute set, get, delete and list only set and delete make sense in the context of ansible.
#     get and list will print their output to the shell so adding them is superflious.
#     Trying to use edit will be skipped altogether to prevent vim (or whatever editor is set) from trying to hijack the shell.
#
# config: 
#   - { config: true, command: 'set', key: 'some key', value: '/Users/cwhite/.atom/.apm' }
#   - { config: true, command: 'delete', key: 'some key'}

### dedupe
#
# Playbook attribute: dedupe
# Required: no
# Type: boolean
# Default: false
# Description:
#   Runs `apm dedupe {{ dedupe.packages }}`
#   Command --help:
#     Usage: apm dedupe [<package_name>...]
#
#     Reduce duplication in the node_modules folder in the current directory.
#
#     This command is experimental.
#
# Note:
#   It appears that you can run this without specifying a package to presumably dedupe all but this has not been tested.
#
# dedupe:
#   - { enable: true, packages: 'some packages' }
