---

# print ansible path
- name: print ansible path
  debug: msg="{{ ansible_env.PATH }}"

# print local path
- name: print local path
  command: echo $PATH

# check if homebrew is installed
- name: check if homebrew is installed
  command: which brew
  register: which_brew_out
  failed_when: which_brew_out.rc
  ignore_errors: true
  # changed_when: false

# install homebrew if necessary
- name: install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew
  when: which_brew_out|failed
