---

# print ansible $path
- name: print ansible $path
  debug: msg="{{ ansible_env.PATH }}"

# register local $path var
- name: echo local $path
  command: echo $PATH
  register: local_path
  no_log: true

# print local $path
- name: print local $path
  debug: msg="{{ local_path.stdout }}"

# check if homebrew is installed
- name: check if homebrew is installed
  command: which brew
  register: which_brew_out
  failed_when: which_brew_out.rc
  ignore_errors: true
  no_log: true

# install homebrew if necessary
- name: install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew
  when: which_brew_out|failed
