---

- name: which ansible
  command: which ansible
  register: which_ansible_out
  failed_when: which_ansible_out.rc
  changed_when: false
  ignore_errors: true

- name: display which ansible
  debug: "msg={{ which_ansible_out.rc }}"

- name: display which ansible
  debug: "msg={{ which_ansible_out.stdout }}"

- name: which brew
  command: which apm git
  register: which_brew_out
  failed_when: which_brew_out.rc
  changed_when: false
  ignore_errors: true

- name: display which brew
  debug: "msg={{ which_brew_out.rc }}"

- name: display which brew
  debug: "msg={{ which_brew_out.stdout }}"

# - name: echo env path
#   command: echo $PATH
#   environment:
#     PATH: /usr/local/bin:{{ ansible_env.PATH }}
#   become_user: cwhite
#   register: env_path_out
#   changed_when: False

# - name: display fixed output
#   debug: "msg={{ env_path_out.stdout }}"

# - name: display ansible path
#   debug: msg="{{ ansible_env.PATH }}"

# ensure apm (atom package manager) is installed
# - name: ensure apm installed
#   command: which apm
#   register: apm_installed_status
#   failed_when: apm_installed_status.rc
#   changed_when: false
#   check_mode: no

# - name: install homebrew
#   shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#   args:
#     creates: /usr/local/bin/brew

# - command: /bin/false
#   register: result
#   ignore_errors: True

# - command: /bin/something
#   when: result|failed
