---
galaxy_info:
  author: Chris White
  description: Ansible role to setup my gaming environment, or as close to it as you can on Mac. 
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system