---
galaxy_info:
  author: Chris White
  description: This role manages dotfiles
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
