---

- name: Disable natural scrolling
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "com.apple.swipescrolldirection"
    type: boolean
    value: false
  notify: "restart macos preferences"

- name: Change Dock position to right
  osx_defaults:
    domain: "com.apple.dock"
    key: "orientation"
    type: string
    value: "right"
  notify: "restart macos preferences"